name: Example workflow
on: push
jobs:
  security:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Run CLI
        uses: raphaelcastilhoc/CLI/actions@main
        env:
          OLYMPIX_API_TOKEN: ${{ secrets.OLYMPIX_API_TOKEN }}
        with:
          args: --output-format json --no-uninitialized-state-variable --no-calls-in-loop --no-default-visibility
